export const data = [
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 1,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 2,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 3,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 4,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 1,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 2,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 3,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 4,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 1,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 2,
    },
    {
        question: "Which device is required for the internet connection",
        option1: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option2: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option3: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        option4: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Velit, enim.",
        ans: 3,
    },
];